// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using FooSpec within kubernetes types, where deepcopy-gen is used.
func (in *FooSpec) DeepCopyInto(out *FooSpec) {
	p := proto.Clone(in).(*FooSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FooSpec. Required by controller-gen.
func (in *FooSpec) DeepCopy() *FooSpec {
	if in == nil {
		return nil
	}
	out := new(FooSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new FooSpec. Required by controller-gen.
func (in *FooSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
