// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for FooSpec
func (this *FooSpec) MarshalJSON() ([]byte, error) {
	str, err := SpecMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for FooSpec
func (this *FooSpec) UnmarshalJSON(b []byte) error {
	return SpecUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	SpecMarshaler   = &jsonpb.Marshaler{}
	SpecUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
